language: csharp
# solution: source/Pl31.ShapesNet.sln

matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      env: MSBUILD="dotnet msbuild"
    - mono: latest
      dotnet: none
      env: MSBUILD="msbuild"

script:
  - $MSBUILD /t:restore source/Pl31.ShapesNet/Pl31.ShapesNet.csproj
  - $MSBUILD /p:Configuration=Release source/Pl31.ShapesNet/Pl31.ShapesNet.csproj
  - $MSBUILD /t:restore source/tests/tests.csproj
  - $MSBUILD /p:Configuration=Release source/tests/tests.csproj
  - $MSBUILD /p:Configuration=Release /t:test source/tests/tests.csproj
