language: csharp
mono: latest

script:
  - msbuild /p:Configuration=Release /t:restore source/Pl31.ShapesNet.sln
  - msbuild /p:Configuration=Release source/Pl31.ShapesNet.sln
  - msbuild /p:Configuration=Release /t:test source/tests/tests.csproj
