language: csharp
solution: source/Pl31.ShapesNet.sln

matrix:
  include:
    - mono: none
      dotnet: latest   
    - mono: latest
      dotnet:none

#mono:
#  - latest
#script:
#  - xbuild /p:Configuration=Release source/Pl31.ShapesNet.sln
#  - mono ./source/packages/NUnit.Runners.*/tools/nunit-console.exe ./source/tests/bin/Release/tests.dll
